alias c="clear"
alias v="nvim"
alias ed="ed -lp '>'"
alias ..="cd .."
alias top="btm"
alias grep="rg"
alias find="fd"
alias ps="procs"

alias ls="exa --icons"
alias la="exa -a --icons"
alias ll="exa -ahl --icons --git"
alias tree="exa -Thl --icons --git"

alias g="git"
alias ga="git add"
alias gc="git commit"
alias gcm="git commit -m"
alias gs="git status -sb"
alias gd="git diff"
alias gb="git branch -a"
alias gp="git push"
alias gch="git checkout"
alias gw="git worktree"
alias gl="git log --graph --oneline"
alias glog="git log --graph -n 10"
alias gsub="git submodule"
alias tig="tig --all"
alias gg="ghq get -p"

